spring:
  application:
    name: forum
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/forum
    username: postgres
    password: 'password@123'

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

